// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[Fail-1]
	_ = x[NoCode-2]
	_ = x[ReqParseErr-1000]
	_ = x[ReqUserIDEmptyErr-2000]
	_ = x[SQLInserErr-3000]
	_ = x[SQLQueryErr-3001]
	_ = x[SQLUpdateErr-3002]
	_ = x[SQLNotFound-3003]
	_ = x[SQLExist-3004]
	_ = x[RPCErr-4000]
	_ = x[RPCTooManyRequest-4001]
	_ = x[ServiceErr-5000]
	_ = x[ServiceErrRetryLater-5001]
	_ = x[ServiceUserExist-5102]
	_ = x[ServiceUserTokenInvalid-5103]
	_ = x[ServiceUserPasswordErr-5104]
	_ = x[ServiceUserPermissionErr-5105]
	_ = x[ServiceWorkspaceInitErr-5156]
	_ = x[ServiceWorkspaceNotEnough-5157]
	_ = x[ServiceWorkspaceNotEnoughPairOpFailed-5158]
	_ = x[ServiceModelSearchErr-5209]
	_ = x[ServiceModelDirExist-5210]
	_ = x[ServiceModelDirNotFound-5211]
	_ = x[ServiceModelIsSymlink-5212]
	_ = x[ServiceModelCreateErr-5213]
	_ = x[ServiceModelDeleteErr-5214]
	_ = x[VolcRpcVolumeErr-5300]
	_ = x[VolcRpcTosErr-5301]
	_ = x[PathIsNotDir-5500]
	_ = x[PathIsNotFile-5501]
	_ = x[PathIsNotExists-5502]
	_ = x[SrcPathIsNotExists-5503]
	_ = x[DstPathIsNotExists-5504]
	_ = x[DstPathIsExists-5505]
	_ = x[CreateFileErr-5506]
	_ = x[DeleteFileErr-5507]
	_ = x[RenameFileErr-5508]
	_ = x[MoveFileErr-5509]
	_ = x[MoveSrcDstNotParentErr-5510]
	_ = x[GetFileMetaErr-5511]
	_ = x[IteratorFileErr-5512]
	_ = x[TaskNotExit-6000]
}

const _ErrCode_name = "成功失败错误码格式不正确请求参数错误controller 层错误数据库错误查询 出错更新 出错查询不存在数据已经存在rpc 错误rpc 请求过多业务层错误服务内部错误，稍后重试用户存在用户 token 无效用户密码错误用户权限错误工作空间初始化失败工作空间不足, 创建同步任务失败工作空间不足, 部分同步任务创建失败模型请求出错模型目录、文件已经存在模型目录、文件不存在模型目录、文件是符号链接创建模型目录、文件失败删除模型目录、文件失败火山弹性块存储 rpc 错误火山对象存储 rpc 错误路径不是目录路径不是文件路径不存在源路径不存在目标路径不存在目标路径已经存在创建文件失败删除文件失败重命名文件失败移动文件失败移动源路径和目标路径不在同级目录获取文件元信息失败迭代文件失败task 错误"

var _ErrCode_map = map[ErrCode]string{
	0:    _ErrCode_name[0:6],
	1:    _ErrCode_name[6:12],
	2:    _ErrCode_name[12:36],
	1000: _ErrCode_name[36:54],
	2000: _ErrCode_name[54:74],
	3000: _ErrCode_name[74:89],
	3001: _ErrCode_name[89:102],
	3002: _ErrCode_name[102:115],
	3003: _ErrCode_name[115:130],
	3004: _ErrCode_name[130:148],
	4000: _ErrCode_name[148:158],
	4001: _ErrCode_name[158:174],
	5000: _ErrCode_name[174:189],
	5001: _ErrCode_name[189:222],
	5102: _ErrCode_name[222:234],
	5103: _ErrCode_name[234:253],
	5104: _ErrCode_name[253:271],
	5105: _ErrCode_name[271:289],
	5156: _ErrCode_name[289:316],
	5157: _ErrCode_name[316:360],
	5158: _ErrCode_name[360:410],
	5209: _ErrCode_name[410:428],
	5210: _ErrCode_name[428:461],
	5211: _ErrCode_name[461:491],
	5212: _ErrCode_name[491:527],
	5213: _ErrCode_name[527:560],
	5214: _ErrCode_name[560:593],
	5300: _ErrCode_name[593:625],
	5301: _ErrCode_name[625:654],
	5500: _ErrCode_name[654:672],
	5501: _ErrCode_name[672:690],
	5502: _ErrCode_name[690:705],
	5503: _ErrCode_name[705:723],
	5504: _ErrCode_name[723:744],
	5505: _ErrCode_name[744:768],
	5506: _ErrCode_name[768:786],
	5507: _ErrCode_name[786:804],
	5508: _ErrCode_name[804:825],
	5509: _ErrCode_name[825:843],
	5510: _ErrCode_name[843:891],
	5511: _ErrCode_name[891:918],
	5512: _ErrCode_name[918:936],
	6000: _ErrCode_name[936:947],
}

func (i ErrCode) String() string {
	if str, ok := _ErrCode_map[i]; ok {
		return str
	}
	return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
